In [1]:
import pandas as pd

ms_data = pd.read_csv("data_health_2023.csv")
ms_data.head()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2023,AL,Alabama,Jefferson,1073,1073010900,BRFSS,Disability,Any disability among adults,%,...,40.7,49.0,"4,719","3,410",POINT (-86.7705771 33.5795996),1073010900,DISABLT,DISABILITY,CrdPrv,Any Disability
1,2023,AL,Alabama,Jefferson,1073,1073011207,BRFSS,Health Outcomes,Depression among adults,%,...,19.9,25.9,"5,103","3,684",POINT (-86.6742325 33.6638358),1073011207,HLTHOUT,DEPRESSION,CrdPrv,Depression
2,2023,AL,Alabama,Lauderdale,1077,1077010100,BRFSS,Disability,Any disability among adults,%,...,34.0,46.2,"2,278","2,093",POINT (-87.6598801 34.7958382),1077010100,DISABLT,DISABILITY,CrdPrv,Any Disability
3,2023,AL,Alabama,Lee,1081,1081040202,BRFSS,Health Outcomes,Arthritis among adults,%,...,20.7,26.2,"3,084","2,459",POINT (-85.4521355 32.6113816),1081040202,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis
4,2023,AL,Alabama,Lee,1081,1081040300,BRFSS,Health Outcomes,Obesity among adults,%,...,29.2,42.2,"2,576","2,188",POINT (-85.4668576 32.6016654),1081040300,HLTHOUT,OBESITY,CrdPrv,Obesity

In [2]:
ms_data['Year'].value_counts()

Year
2023    2629753
2022     417531
Name: count, dtype: int64

In [3]:
ms_data_2 = pd.read_csv("data_health_2022.csv") 
ms_data_2.head()

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPop18plus,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2022,AL,Alabama,Sheffield,BRFSS,Health Outcomes,All teeth lost among adults aged >=65 years,%,Age-adjusted prevalence,23.4,...,19.8,27.1,"7,384","9,403",POINT (-87.6981825 34.757028),169648,HLTHOUT,TEETHLOST,AgeAdjPrv,All Teeth Lost
1,2022,AL,Alabama,Courtland,BRFSS,Health Outcomes,All teeth lost among adults aged >=65 years,%,Age-adjusted prevalence,20.6,...,16.9,24.2,469,583,POINT (-87.3278925 34.6699456),118040,HLTHOUT,TEETHLOST,AgeAdjPrv,All Teeth Lost
2,2022,AL,Alabama,Mount Olive,BRFSS,Health Outcomes,All teeth lost among adults aged >=65 years,%,Age-adjusted prevalence,18.7,...,15.1,22.5,243,311,POINT (-86.1330402 33.0784543),152320,HLTHOUT,TEETHLOST,AgeAdjPrv,All Teeth Lost
3,2022,AL,Alabama,Nanafalia,BRFSS,Health Outcomes,All teeth lost among adults aged >=65 years,%,Age-adjusted prevalence,19.3,...,15.9,22.9,68,75,POINT (-87.9957573 32.1113928),153208,HLTHOUT,TEETHLOST,AgeAdjPrv,All Teeth Lost
4,2022,AL,Alabama,Hobson City,BRFSS,Health Outcomes,All teeth lost among adults aged >=65 years,%,Age-adjusted prevalence,24.7,...,20.8,29.0,562,759,POINT (-85.8461462 33.6188012),135152,HLTHOUT,TEETHLOST,AgeAdjPrv,All Teeth Lost

In [4]:
ms_data_2['Year'].value_counts()

Year
2023    1851248
2022     299190
Name: count, dtype: int64